carts/urls.py
from django.urls import path
from . import views

# app_name = 'carts'
urlpatterns = [
	#path('remove/<int:cart_id>/', views.cart_add, name='cart_remove'),
	path('checkout/', views.checkout, name='checkout'),
	path('', views.carts, name='carts'),
]

comingsoon/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.coming, name='coming'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
	# product_detail/2/
	path('<int:prod_id>/', views.product_detail, name='product_detail'),
	# path('<int:prod_id>/', views.detail, name='detail'),
]

shop2but1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('comingsoon/', include('comingsoon.urls')),
    path('product_details/', include('products.urls')),
	path('carts/', include('carts.urls')),
	path('', views.home, name='home'),
    path('admin/', admin.site.urls),
]

carts/models.py
from django.db import models
from products.models import *
# Create your models here.

class cart(models.Model):
	cart_id = models.AutoField(primary_key = True)
	infor_name = models.CharField(max_length = 50, blank = True, null = True)
	infor_address = models.CharField(max_length = 200, blank = True, null = True)
	infor_phone = models.CharField(max_length = 20, blank = True, null = True)

	
	# def __str__(self):
	# 	return self.infor_name
	# def __str__(self):
	# 	return self.infor_address
	# def __str__(self):
	# 	return self.infor_phone

class cartItem(models.Model):
	cart_id = models.ForeignKey(cart, on_delete = models.CASCADE)
	prod_id = models.ForeignKey(product, on_delete = models.CASCADE)

comingsoon/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
# Create your models here.

class category(models.Model):
	cate_id = models.AutoField(primary_key = True)
	cate_name = models.CharField(max_length = 100)

	def __str__(self):
		return self.cate_name

class product(models.Model):
	prod_id = models.AutoField(primary_key = True)
	cate_id = models.ForeignKey(category, on_delete = models.CASCADE)
	prod_name = models.CharField(max_length = 100)
	prod_price = models.DecimalField(max_digits=6, decimal_places=3)
	prod_description = models.TextField()
	prod_imgage = models.CharField(max_length = 30)
	prod_imgage_detail = models.CharField(max_length = 50, null = True)
	prod_status = models.BooleanField(default = True)

carts/views.py
from django.shortcuts import render
from django.template import loader
# Create your views here.

from django.http import HttpResponse
from products.models import *
from carts.models import *

def carts(request):
	item = product.objects.filter(cartitem__cart_id=1)

	context = {
		'item' : item,
		'count' : item.count()
	}

	return render(request, 'store/carts.html', context)

def checkout(request):
    return render(request, 'store/checkout.html')

comingsoon/views.py
from django.shortcuts import render
from django.template import loader
# Create your views here.

from django.http import HttpResponse

def coming(request):
    return render(request, 'coming.html')

products/views.py
from django.shortcuts import render
from django.http import Http404
from django.template import loader

from .models import *
# Create your views here.

from django.http import HttpResponse

def product_detail(request, prod_id):
	try:
		prod = product.objects.get(pk=prod_id)
	except product.DoesNotExist:
		raise Http404("hehee")
	return render(request, 'store/product_detail.html', {'prod': prod})

shop2but1/views.py
from django.shortcuts import render
from django.template import loader
# Create your views here.

from django.http import HttpResponse
from products.models import *
from carts.models import *

def home(request):
	cate = category.objects.all()
	prod = product.objects.all()
	context = {
		'category' : cate,
		'product' : prod
	}
	return render(request, 'home.html', context)

templates/base.html
{% load static %}

<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}| Store2But1</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Place favicon.ico in the root directory -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    <link rel="apple-touch-icon" href="{% static 'apple-touch-icon.png' %}">
    

    <!-- All css files are included here. -->
    <!-- Bootstrap fremwork main css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Owl Carousel main css -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <!-- This core.css file contents all plugings css file. -->
    <link rel="stylesheet" href="{% static 'css/core.css' %}">
    <!-- Theme shortcodes/elements style -->
    <link rel="stylesheet" href="{% static 'css/shortcode/shortcodes.css' %}">
    <!-- Theme main style -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!-- Responsive css -->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <!-- User style -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

<style>
/* width */
::-webkit-scrollbar {
  width: 10px;
}

/* Track */
::-webkit-scrollbar-track {
  box-shadow: inset 0 0 5px grey; 
  border-radius: 10px;
}
 
/* Handle */
::-webkit-scrollbar-thumb {
  background: #7eac8d; 
  border-radius: 10px;
}

/* Handle on hover */
::-webkit-scrollbar-thumb:hover {
  background: #7eac8d; 
}
</style>

    <!-- Modernizr JS -->
    <script src="{% static 'js/vendor/modernizr-2.8.3.min.js' %}"></script>
</head>

<body>  

    <!-- Body main wrapper start -->
    <div class="wrapper fixed__footer">
            {% include 'includes/navbar.html' %}

            {% block content %}

            <!-- content -->

            {% endblock %}

            {% include 'includes/footer.html' %}
    </div>
    <!-- Body main wrapper end -->


    {% block quickview %}
    <!-- QUICKVIEW PRODUCT -->
    {% endblock %}



    <!-- jquery latest version -->
    <script src="{% static 'js/vendor/jquery-1.12.0.min.js' %}"></script>
    <!-- Bootstrap framework js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- All js plugins included in this file. -->
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <!-- Waypoints.min.js. -->
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <!-- Main js file that contents all jQuery plugins activation. -->
    <script src="{% static 'js/main.js' %}"></script>






</body>

</html>

templates/coming.html
<!-- 
Author URI: http://webthemez.com/ 
-->
{% load static %}

<!doctype html>
<!--[if IE 7 ]>
<html lang="en-gb" class="isie ie7 oldie no-js">
    <![endif]-->
    <!--[if IE 8 ]>
    <html lang="en-gb" class="isie ie8 oldie no-js">
        <![endif]-->
        <!--[if IE 9 ]>
        <html lang="en-gb" class="isie ie9 no-js">
            <![endif]-->
            <!--[if (gt IE 9)|!(IE)]>
            <!-->
<html lang="en-gb" class="no-js">
<!--
<![endif]-->
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<!--[if lt IE 9]>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<![endif]-->
<title>Coming Soon... | Store2but1</title>
<link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
<meta name="description" content="">
<meta name="author" content="WebThemez">
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<!--[if lte IE 8]>
<script type="text/javascript" src="http://explorercanvas.googlecode.com/svn/trunk/excanvas.js"></script>
<![endif]-->
<link rel="stylesheet" href="{% static 'css/css2/bootstrap.min.css' %}" />
<link href="{% static 'css/css2/animate.css' %}" rel="stylesheet" media="screen">
<link rel="stylesheet" href="{% static 'css/css2/styles.css' %}" />
<link href="{% static 'fonts/fonts2/css/font-awesome.min.css' %}" rel="stylesheet">
</head>
<body>
	<!--/.header-->
	<section id="home">
		<div class="banner-container">
			<div class="container">
				<div class="row">
					<div class="logo">
						<img src="{% static 'images/images2/logo.png' %}" alr='logo'/>
					</div>
				</div>
				<div class="heading text-center">
					<h2>Coming soon!!!</h2>
					<!-- <strong>Stay tuned!!</strong> -->
				</div>
				<div class="countdown styled"></div>
				<div class="row">
					<!-- <div class="heading text-center sub">  
					</div> -->
					<!-- <form class="newsLetter" action="" method="post">
						<div class="subscribe">
							<input class="form-control" type="email" placeholder="Get subscribe with your email ID">
								<button type="submit" class="btn">
									<i class="fa fa-envelope"></i>
								</button>
							</div>
							
						</form> -->
					</div>
				</div>
			</div>
		</section>
		<footer>
			<div class="container">
				<div class="social text-center">
					<a href="https://www.facebook.com/tranthuc12321/">
						<i class="fa fa-facebook"></i>
					<a href="https://github.com/tranthuc99">
						<i class="fa fa-github"></i>
					</a>
				</div>
				<div class="clear"></div>
				<!--CLEAR FLOATS-->
			</div>
		</footer>
		<!--/.page-section-->
		<section class="copyright">
			<div class="container">
				<div class="row">
					<!-- <div class="col-sm-12 text-center"> Copyright 2018 | All Rights Reserved - <a href="https://webthemez.com/tag/free" target="_blank">Free HTML Templates</a> by WebThemez. 
					</div> -->
				</div>
				<!-- / .row -->
			</div>
		</section>
		<!--[if lte IE 8]>
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
		<![endif]-->
		<script src="{% static 'js/js2/modernizr-latest.js' %}"></script>
		<script src="{% static 'js/js2/jquery-1.8.2.min.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/js2/bootstrap.min.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/js2/jquery.nav.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/js2/waypoints.js' %}"></script>
		<script src="{% static 'js/js2/Backstretch.js' %}" type="text/javascript"></script>






		<script>
		$( function() {
		        var endDate = "December  30, 2025 14:08:00";

		        $('.countdown.simple').countdown({ date: endDate });

		        $('.countdown.styled').countdown({
		          date: endDate,
		          render: function(data) {
		            $(this.el).html("<div>" + this.leadingZeros(data.days, 3) + " <span>days</span></div><div>" + this.leadingZeros(data.hours, 2) + " <span>hrs</span></div><div>" + this.leadingZeros(data.min, 2) + " <span>min</span></div><div>" + this.leadingZeros(data.sec, 2) + " <span>sec</span></div>");
		          }
		        });

		        $('.countdown.callback').countdown({
		          date: +(new Date) + 10000,
		          render: function(data) {
		            $(this.el).text(this.leadingZeros(data.sec, 2) + " sec");
		          },
		          onEnd: function() {
		            $(this.el).addClass('ended');
		          }
		        }).on("click", function() {
		          $(this).removeClass('ended').data('countdown').update(+(new Date) + 10000).start();
		        });
				
				
				
		      });
		   
		   
		var customScripts = {
		 
		    onePageNav: function () {

		        $('#mainNav').onePageNav({
		            currentClass: 'active',
		            changeHash: false,
		            scrollSpeed: 950,
		            scrollThreshold: 0.2,
		            filter: '',
		            easing: 'swing',
		            begin: function () {
		                //I get fired when the animation is starting
		            },
		            end: function () {
		                   //I get fired when the animation is ending
						if(!$('#main-nav ul li:first-child').hasClass('active')){
							$('.header').addClass('addBg');
						}else{
								$('.header').removeClass('addBg');
						}
						
		            },
		            scrollChange: function ($currentListItem) {
		                //I get fired when you enter a section and I pass the list item of the section
						if(!$('#main-nav ul li:first-child').hasClass('active')){
							$('.header').addClass('addBg');
						}else{
								$('.header').removeClass('addBg');
						}
					}
		        });
				
				$("a[href='#top']").click(function () {
		                $("html, body").animate({ scrollTop: 0 }, "slow");
		                return false;
		            });
					$("a[href='#basics']").click(function () {
		                $("html, body").animate({ scrollTop: $('#services').offset().top}, "slow"); 
		                return false;
		            });
		    },   
			waySlide: function(){
				  	/* Waypoints Animations
				   ------------------------------------------------------ */		   			  			
					$('#services').waypoint(function() {				
					$('#services .col-md-3').addClass( 'animated fadeInUp show' );   
					}, { offset: 800}); 
					$('#aboutUs').waypoint(function() {				
					$('#aboutUs').addClass( 'animated fadeInUp show' );   
					}, { offset: 800}); 
					$('#contactUs').waypoint(function() {				
					$('#contactUs .parlex-back').addClass( 'animated fadeInUp show' );   
					}, { offset: 800}); 
					 						 
				}, 
		    init: function () {
		        customScripts.onePageNav();  
				customScripts.waySlide(); 
		    }
		}
		$('document').ready(function () {
			 $.backstretch([
		      "{% static 'images/images2/img1.jpg' %}"
		    , "{% static 'images/images2/img2.jpg' %}"
		  ], {duration: 9000, fade: 1250});
		  
		    customScripts.init();
			$('#services .col-md-3, #features, #aboutUs, #clients, #portfolio, #plans, #contactUs .parlex-back').css('opacity','0');
			$( "#menuToggle" ).toggle(function() {
			$(this).find('i').removeClass('fa-bars').addClass('fa-remove');
			 $('#mainNav').animate({"right":"0px"}, "slow");
			}, function() {
			  $('#mainNav').animate({"right":"-200px"}, "slow");
			  $(this).find('i').removeClass('fa-remove').addClass('fa-bars');
			});	
		});
		</script>








		<script type="text/javascript" src="{% static 'js/js2/jquery.countdown.js' %}"></script>
	</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Trang chủ
{% endblock %}

        {% block content %}

        <!-- Start Bradcaump area -->
        <div class="ht__bradcaump__area" style="background: rgba(0, 0, 0, 0) url({% static 'images/bg/3.jpg' %}) no-repeat scroll center center / cover ;">
            <div class="ht__bradcaump__wrap">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="bradcaump__inner text-center">
                                <h2 class="bradcaump-title">2But1 - Secondhand Clothing</h2>
                                <nav class="bradcaump-inner">
                                  <a class="breadcrumb-item" href="{% url 'home' %}">Trang chủ</a>
                                  <span class="brd-separetor">/</span>
                                  <span class="breadcrumb-item active">2 but 1</span>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Bradcaump area --> 
        <!-- Start Our Product Area -->
        <section class="htc__product__area shop__page ptb--130 bg__white">
            <div class="container">
                <div class="htc__product__container">
                    <!-- Start Product MEnu -->
                    <div class="row">
                        <div class="col-md-12">
                            <div class="filter__menu__container">
                                <div class="product__menu">
                                    {% for cate in category %}
                                    <button>{{ cate.cate_name }}</button>
                                    {% endfor %}
                                </div>
                                <!-- <div class="filter__box">
                                    <a class="filter__menu" href="#">Bộ lọc</a>
                                </div> -->
                            </div>
                        </div>
                    </div>
                    <!-- End Product MEnu -->
                    <div class="row">
                        <div class="product__list another-product-style">
                            {% for p in product %}
                            <!-- Start Single Product -->
                            <div class="col-md-3 single__pro col-lg-3 cat--1 col-sm-4 col-xs-12">
                                <div class="product foo">
                                    <div class="product__inner">
                                        <div class="pro__thumb">
                                            <a href="{% url 'products:product_detail' p.prod_id %}">
                                                <img src="{% static p.prod_imgage %}" alt="product images">
                                            </a>
                                        </div>
                                        <div class="product__hover__info">
                                            <ul class="product__action">
                                                <!-- <li><a data-toggle="modal" data-target="#productModal" title="Xem nhanh" class="quick-view modal-view detail-link" href="#"><span class="ti-plus"></span></a></li> -->
                                                {% if p.prod_status %}
                                                <li><a title="Thêm vào giỏ" href="{% url 'carts' %}"><span class="ti-shopping-cart"></span></a></li>
                                                <li><a title="Yêu thích" href="#"><span class="ti-heart"></span></a></li>
                                                {% else %}
                                                <h2>SOLD OUT</h2>
                                                {% endif %}
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="product__details">
                                        <h2><a href="{% url 'products:product_detail' p.prod_id %}">{{ p.prod_name }}</a></h2>
                                        <ul class="product__price">
                                            <!-- <li class="old__price">$16.00</li> -->
                                            <li class="new__price">₫{{ p.prod_price }}</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <!-- End Single Product -->
                            {% endfor %}
                        </div>
                    </div>
                    <!-- Start Load More BTn -->
                    <div class="row mt--60">
                        <div class="col-md-12">
                            <div class="htc__loadmore__btn">
                                <a href="{% url 'coming' %}">Xem thêm</a>
                            </div>
                        </div>
                    </div>
                    <!-- End Load More BTn -->
                </div>
            </div>
        </section>
        <!-- End Our Product Area -->

        {% endblock %}

templates/store/carts.html
{% extends 'home.html' %}
{% load static %}
{% load carts_extra %}

{% block title %}
Giỏ hàng
{% endblock %}

		{% block content %}
        <!-- Start Bradcaump area -->
        <div class="ht__bradcaump__area" style="background: rgba(0, 0, 0, 0) url({% static 'images/bg/3.jpg' %}) no-repeat scroll center center / cover ;">
            <div class="ht__bradcaump__wrap">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="bradcaump__inner text-center">
                                <h2 class="bradcaump-title">Giỏ hàng</h2>
                                <nav class="bradcaump-inner">
                                  <a class="breadcrumb-item" href="{% url 'home' %}">Trang chủ</a>
                                  <span class="brd-separetor">/</span>
                                  <span class="breadcrumb-item active">Giỏ hàng</span>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Bradcaump area -->
        <!-- cart-main-area start -->
        <div class="cart-main-area ptb--120 bg__white">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <form action="#">               
                            <div class="table-content table-responsive">
                                <table>
                                    <thead>
                                        <tr>
                                            <th class="product-thumbnail">Ảnh sản phẩm</th>
                                            <th class="product-name">Tên sản phẩm</th>
                                            <th class="product-price">Giá</th>
                                            <!-- <th class="product-quantity">Quantity</th>
                                            <th class="product-subtotal">Total</th> -->
                                            <th class="product-remove">Xóa</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for i in item %}
                                        <tr>
                                            <td class="product-thumbnail"><a href="{% url 'products:product_detail' i.prod_id %}"><img src="{% static i.prod_imgage %}" alt="product img" /></a></td>
                                            <td class="product-name"><a href="{% url 'products:product_detail' i.prod_id %}">{{ i.prod_name }}</a></td>
                                            <td class="product-price"><span class="amount">₫{{ i.prod_price }}</span></td>
                                            <!-- <td class="product-quantity"><input type="number" value="1" /></td>
                                            <td class="product-subtotal">£165.00</td> -->
                                            <td class="product-remove"><a href="#">X</a></td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <div class="row">
                                <div class="col-md-8 col-sm-7 col-xs-12">
                                    <div class="buttons-cart">
                                        <input type="submit" value="Cập nhật giỏ" />
                                        <a href="{% url 'home' %}">Tiếp tục mua</a>
                                    </div>
                                    <!-- <div class="coupon">
                                        <h3>Coupon</h3>
                                        <p>Enter your coupon code if you have one.</p>
                                        <input type="text" placeholder="Coupon code" />
                                        <input type="submit" value="Apply Coupon" />
                                    </div> -->
                                </div>
                                <div class="col-md-4 col-sm-5 col-xs-12">
                                    <div class="cart_totals">
                                        <h2>Đơn hàng</h2>
                                        <table>
                                            <tbody>
                                                <tr class="cart-subtotal">
                                                    <th></th>
                                                    <td><span class="amount">Giỏ có {{ count }} sản phẩm</span></td>
                                                </tr>
                                                <tr class="cart-subtotal">
                                                    <th>Tổng tiền hàng</th>
                                                    <td><span class="amount">₫{{ item|total }}</span></td>
                                                </tr>
                                                <tr class="shipping">
                                                    <th>Phí vận chuyển</th>
                                                    <td>
                                                        <ul id="shipping_method">
                                                            <li>
                                                                <!-- <input type="radio" /> --> 
                                                                <label>
                                                                    <!-- Flat Rate:  --><span class="amount">₫30.000</span>
                                                                </label>
                                                            </li>
                                                            <!-- <li>
                                                                <input type="radio" /> 
                                                                <label>
                                                                    Free Shipping
                                                                </label>
                                                            </li> -->
                                                            <li></li>
                                                        </ul>
                                                        <!-- <p><a class="shipping-calculator-button" href="#">Calculate Shipping</a></p> -->
                                                    </td>
                                                </tr>
                                                <tr class="order-total">
                                                    <th>Tổng cộng</th>
                                                    <td>
                                                        <strong><span class="amount">₫{{ item|sumtotal }}</span></strong>
                                                    </td>
                                                </tr>                                           
                                            </tbody>
                                        </table>
                                        <div class="wc-proceed-to-checkout">
                                            <a href="{% url 'checkout' %}">Xử lý thanh toán</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form> 
                    </div>
                </div>
            </div>
        </div>
        <!-- cart-main-area end -->
        {% endblock %}